name: Deploy to Surge.sh

on:
  push:
    branches:
      - main  # Puedes cambiar esto a la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Puedes cambiar esto a la versión de Node.js que necesites

    - name: Deploy to Surge.sh
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: |
        npm install --global surge
        surge . https://1er-parcial.surge.sh
